### ISSUE TITLE
[server] feat: logger 설정

### ISSUE THREAD

**Issue by anjm1020** [TeamDivers/Soar#29]
## Description

- 서버 로그 수집 설정

## Todo

- [x] 로그 수집 설정
- [x] 스프링-로그백으로 파일 형태로 로그 저장

**Comment by kangCoder** [comment]
- 날짜 별로 ./log/날짜.log 파일에 로그 수집하도록 설정
- dev|create profile에서는 콘솔에 INFO level로 로그 출력
- prod profile에서는 콘솔 및 파일에 ERROR level로 로그 출력
