### ISSUE TITLE
[client] 버튼 수정

### ISSUE THREAD

**Issue by janghoosa** [TeamDivers/Soar#33]
## Description

- 작성하기 버튼 크기랑 위치가 이상해요
<img width="1024" alt="스크린샷 2023-08-14 오후 11 15 06" src="https://github.com/TeamDivers/Soar/assets/39695780/8c0caa4f-3c05-4d50-8ba7-4b928ce316d9">

## Todo

- [ ] 수정해줘.

**Comment by Jinho1011** [comment]
모바일 화면 크기를 가정하고 구현한거라서 냅뒀는데 일단 후순위 이슈로 고려해두겠습니다.
